### ISSUE TITLE
Remove generics-sop dependency

### ISSUE THREAD

**Issue by mitchellwrosen** [feuerbach/yaml-combinators#2]
Hi Roman, thank you for the fantastic library!

Would you accept a patch to remove `generics-sop` as a dependency? I'd prefer not to pull in the orphan `Generic` instance of `Value`.

**Comment by UnkindPartition** [comment]
Not sure — could you elaborate on the problem and your proposed solution?

**Comment by mitchellwrosen** [comment]
The problem is only that this orphan `Generic` instance doesn't seem to belong in this library (it would clash with any other library that wants to use `generics-sop` on `Value`).

My proposed solution is simply to rewrite `Parser` in a "dumb" way as you outlined in your article:

```haskell
data Parser a = Parser
  (Maybe (Object -> Either ParseError a))
  (Maybe (Array -> Either ParseError a))
  ...
```

**Comment by UnkindPartition** [comment]
I'd rather not support the unrolled version. If this presents a problem, I'd accept a patch introducing a cabal flag hiding the instance + ci configuration that tests both versions.

**Comment by UnkindPartition** [comment]
Closing because I don't plan to remove the generics-sop dependency and otherwise it is not actionable on my part; but my offer still stands.

**Comment by mitchellwrosen** [comment]
No problem, I will take you up on the offer when it actually bites me =)
