### ISSUE TITLE
Shortcut to (Parse Value)?

### ISSUE THREAD

**Issue by trilogysci** [feuerbach/yaml-combinators#3]
Is there a simplified way to create a Parse Value without having to <|> each type? In situations where it can except any valid expression such as
(,) <$> field "name" string <*> field "value" parseValue
:: Parse (Text, Value)

**Comment by UnkindPartition** [comment]
Good idea. I just added one, called anyValue, to master. Could you try it and see if it does the job for you?

**Comment by UnkindPartition** [comment]
I haven't heard from you, so I went ahead and released this as yaml-combinators-1.1.1.
