### ISSUE TITLE
object parser with additional fields

### ISSUE THREAD

**Issue by symbiont-eric-torreborre** [feuerbach/yaml-combinators#7]
Would you accept a PR for a `object'` function which would not validate that all fields are consumed like in the current `object` function? Or maybe am I missing a good way to deal with this use case?

**Comment by UnkindPartition** [comment]
Sure. I can't think of a good name for that function though. Maybe add an argument to the `object` function, which would have an algebraic sum type with two constructors (check/don't check)? How to name the type and constructors would also need some thinking.

**Comment by symbiont-eric-torreborre** [comment]
Why not something like `object`/`objectLenient`? This way:

 - there's only one name to find
 - we don't change the meaning of the existing `object` function
 - we use `lenient` as an indicator that we are less strict than the `object` function

**Comment by UnkindPartition** [comment]
First, I don't think `objectLenient` is descriptive enough. With an argument, we can do something like

```
data ExtraFields = ExtraFieldsAllowed | ExtraFieldsNotAllowed
```

which conveys more meaning than just "lenient".

Second, it scales better. If tomorrow we need another option to modify the behaviour of `object`, we'd have 4 different functions which do more or less the same with slight variations.

**Comment by symbiont-eric-torreborre** [comment]
Well that works for me :-). Do you want to do it or you prefer that I make a PR?

**Comment by UnkindPartition** [comment]
Yes, please make a PR.

**Comment by etorreborre** [comment]
Here it is: https://github.com/feuerbach/yaml-combinators/pull/8

**Comment by etorreborre** [comment]
Thanks, I actually thought about a similar solution at some point but forgot to mention it :-)
